import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { CategoryProvider } from "@/context/CategoryContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto max-w-screen-lg">
          <CategoryProvider>
            <div className="flex min-h-screen flex-col items-center p-24">
              {children}
            </div>
          </CategoryProvider>
        </div>
      </body>
    </html>
  );
}
